"""Expose the reviewed lossless PasswordSafe service and safe domain surface."""

from .constants import (
    CURRENT_FORMAT_VERSION,
    MINIMUM_ITERATIONS,
    FieldKind,
    FormatVersion,
    HeaderFieldType,
    RecordFieldType,
    ResourceLimits,
)
from .errors import (
    AuthenticationError,
    AuthenticationReason,
    CryptoBackendError,
    CryptoBackendReason,
    ExternalModificationError,
    FailureReason,
    FailureStage,
    IncompatibleExportError,
    IncompatibleExportReason,
    IntegrityError,
    IntegrityReason,
    MalformedReason,
    MalformedVaultError,
    OperationReason,
    PasswordSafeError,
    ProtectedRecordError,
    RecoveryAvailableError,
    ResourceLimitError,
    ResourceLimitReason,
    StaleRevisionError,
    StorageError,
    StorageReason,
    UnsavedChangesError,
    UnsupportedFormatError,
    UnsupportedFormatReason,
)
from .model import PreservationWarning, PreservationWarningCode, RecordHandle, RevisionToken
from .secrets import SecretBuffer, SecretClosedError, SecretLease
from .service import SaveResult, VaultService
from .session import (
    Change,
    NewRecord,
    RecordView,
    RemoveField,
    SetBytesField,
    SetSecretField,
    SetTextField,
    SetTimeField,
    SetUInt32Field,
    VaultSession,
)
from .storage import RecoveryRevision



__all__ = (
    "CURRENT_FORMAT_VERSION",
    "MINIMUM_ITERATIONS",
    "AuthenticationError",
    "AuthenticationReason",
    "Change",
    "CryptoBackendError",
    "CryptoBackendReason",
    "ExternalModificationError",
    "FailureReason",
    "FailureStage",
    "FieldKind",
    "FormatVersion",
    "HeaderFieldType",
    "IncompatibleExportError",
    "IncompatibleExportReason",
    "IntegrityError",
    "IntegrityReason",
    "MalformedReason",
    "MalformedVaultError",
    "NewRecord",
    "OperationReason",
    "PasswordSafeError",
    "PreservationWarning",
    "PreservationWarningCode",
    "ProtectedRecordError",
    "RecordFieldType",
    "RecordHandle",
    "RecordView",
    "RecoveryAvailableError",
    "RecoveryRevision",
    "RemoveField",
    "ResourceLimitError",
    "ResourceLimitReason",
    "ResourceLimits",
    "RevisionToken",
    "SaveResult",
    "SecretBuffer",
    "SecretClosedError",
    "SecretLease",
    "SetBytesField",
    "SetSecretField",
    "SetTextField",
    "SetTimeField",
    "SetUInt32Field",
    "StaleRevisionError",
    "StorageError",
    "StorageReason",
    "UnsavedChangesError",
    "UnsupportedFormatError",
    "UnsupportedFormatReason",
    "VaultService",
    "VaultSession",
)
